power.data <- read.table("household_power_consumption.txt", na.strings = "?", header = TRUE, sep=";")
power.data[,1] = as.Date(power.data[,1],format="%d/%m/%Y")
power.data <- subset(power.data, Date == "2007-02-01" | Date == "2007-02-02")
power.data$DateTime <- as.POSIXct(paste(power.data$Date, power.data$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfrow=c(2, 2))
plot(power.data$DateTime, power.data$Global_active_power, ylab="Global Active Power", xlab="", type="l")
plot(power.data$DateTime, power.data$Voltage, ylab="Voltage", xlab="datetime", type="l")
plot(power.data$DateTime, power.data$Sub_metering_1, ylab="Energy sub metering", xlab="", type="n")
lines(power.data$DateTime, power.data$Sub_metering_1)
lines(power.data$DateTime, power.data$Sub_metering_2, col="red")
lines(power.data$DateTime, power.data$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3") ,lty=1, col=c("black","red","blue"),bty="n",cex=0.94)
plot(power.data$DateTime, power.data$Global_reactive_power, ylab="Global_reactive_power", xlab="datetime", type="l")
dev.off()